#!/bin/bash
STAMP=$(date +%Y%m%d_%H%M%S)
source $HOME/.lxrpi_email.conf
HOSTNAME=$(hostname)
MYIP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
MSGFILE=/tmp/emailbody
ME=$(whoami)
SCRIPTFILE=$(basename "$0")
SUBJECT="Update LXRPi: "$HOSTNAME

echo "Email generated by "$SCRIPTFILE" on "$HOSTNAME" by "$ME > $MSGFILE
echo `date` >> $MSGFILE
echo "RPi System: "$HOSTNAME >> $MSGFILE
echo "My IP Address: "$MYIP >> $MSGFILE
echo ""

echo "=============================================================" >> $MSGFILE
echo "Updating LXRPi" >> $MSGFILE
if [ ! -d $HOME/lxrpi ]; then
	cd $HOME/lxrpi;
	git reset --hard origin/master  >> $MSGFILE
	git pull >> $MSGFILE
	cd $HOME;
	echo "=============================================================" >> $MSGFILE
	echo "ssh into "$MYIP" and run command:" >> $MSGFILE
	echo "newbash" >> $MSGFILE
	echo "OR" >> $MSGFILE
	echo "source $HOME/.bashrc" >> $MSGFILE
else
	echo "$HOME/lxrpi directory has been moved or deleted." >> $MSGFILE
	echo "Unable to continue." >> $MSGFILE
fi
echo "=============================================================" >> $MSGFILE

sendemail -f $FROM -t $TO -u $SUBJECT -o message-file=$MSGFILE -s $SERVER -xu $USER -xp $PASS -o tls=auto -v

rm -f $MSGFILE