#!/bin/bash
STAMP=$(date +%Y%m%d_%H%M%S)
source $HOME/.lxrpi_email.conf
HOSTNAME=$(hostname)
MYIP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
MSGFILE=/tmp/emailbody
ME=$(whoami)
SCRIPTFILE=$(basename "$0")
SUBJECT="Update Status: "$HOSTNAME

echo "Email generated by "$SCRIPTFILE" on "$HOSTNAME" by "$ME > $MSGFILE
echo `date` >> $MSGFILE
echo "RPi System: "$HOSTNAME >> $MSGFILE
echo "My IP Address: "$MYIP >> $MSGFILE
echo ""

sudo apt update
echo "=============================================================" >> $MSGFILE
echo "Apt Updates Available" >> $MSGFILE
sudo apt list --upgradable >> $MSGFILE
echo "=============================================================" >> $MSGFILE

echo ""
echo "To install updates" >> $MSGFILE
echo "ssh into "$MYIP" and run command:" >> $MSGFILE
echo "apt-fullup" >> $MSGFILE
echo "OR" >> $MSGFILE
echo "apt-autoup" >> $MSGFILE
echo "OR" >> $MSGFILE
echo "sudo apt-get update; sudo apt-get upgrade" >> $MSGFILE
echo "" >> $MSGFILE
echo "Run lxup from the shell to to update LXRPi" >> $MSGFILE

sendemail -f $FROM -t $TO -u $SUBJECT -o message-file=$MSGFILE -s $SERVER -xu $USER -xp $PASS -o tls=auto -v

rm -f $MSGFILE